apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kubectl-jenkins-context
data:
  kubectl-config-context.sh: |-
    #!/bin/bash -v
    
    kubectl config set-credentials jenkins --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    kubectl config set-cluster kubernetes --server=https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT --certificate-authority="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    kubectl config set-context jenkins-kubernetes --cluster=kubernetes --user=jenkins --namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    kubectl config use-context jenkins-kubernetes

    chmod 777 ~/.kube/config

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
        tier: jenkins
    spec:
      serviceAccountName: jenkins
      initContainers:
      - image: lachlanevenson/k8s-kubectl:v1.11.2
        name: kubectl-config
        command:
        - "/bin/sh"
        args:
        - "/kubectl-config-context.sh"
        volumeMounts:
        - name: kubeconfig
          mountPath: "/root/.kube"
        - name: kubectl-jenkins-context
          mountPath: "/kubectl-config-context.sh"
          subPath: "kubectl-config-context.sh"
      containers:
      - image: aaquiff/jenkins-docker-kube
        name: jenkins
        env:
        - name: WSO2_USERNAME
          valueFrom:
            secretKeyRef:
              name: wso2-credentials
              key: username
        - name: WSO2_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wso2-credentials
              key: password
        imagePullPolicy: Always
        # readinessProbe:
        #   exec:
        #     command:
        #     - wum version
        #     - docker version
        #     - kubectl version
        securityContext:
          runAsUser: 0
          # privileged: true
        # env:
        # - name: CASC_JENKINS_CONFIG
        #   value: "/casc_configs"
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
        - name: docker
          mountPath: /var/run/docker.sock
        - name: jenkins-persistent-storage
          mountPath: /var/jenkins_home
        - name: wso2-credentials
          mountPath: /wso2creds
        # - name: jenkins-conf-storage
        #   mountPath: /var/casc_configs
        # - name: wum-claim-storage
        #   mountPath: /root/.wum3
        ports:
        - containerPort: 8080
          name: jenkins
          protocol: TCP
      volumes:
      - name: kubectl-jenkins-context
        configMap:
          name: kubectl-jenkins-context
          items:
          - key: kubectl-config-context.sh
            path: kubectl-config-context.sh
      - name: jenkins-init
        configMap:
          name: jenkins-init
          items:
          - key: jenkins-init.sh
            path: jenkins-init.sh
      - name: kubeconfig
        emptyDir: {}
      - name: docker
        hostPath:
          path: /var/run/docker.sock
      - name: jenkins-persistent-storage
        persistentVolumeClaim:
          claimName: jenkins-claim
      - name: wso2-credentials
        secret:
          secretName: wso2-credentials
      # - name: wum-claim-storage
      #   persistentVolumeClaim:
      #     claimName: wum-claim
      # - name: jenkins-conf-storage
      #   configMap:
      #     name: jenkins-conf