# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins-service
#   labels:
#     app: jenkins
# spec:
#   ports:
#     - port: 8080
#       targetPort: 8080
#   selector:
#     app: jenkins
#     tier: jenkins
#   type: NodePort

# # ---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
  - name: servlet-http
    port: 8080
    targetPort: 8080
    protocol: TCP
  # - name: servlet-https
  #   port: 9443
  #   targetPort: 9443
  #   protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/affinity: "cookie"
    # nginx.ingress.kubernetes.io/session-cookie-name: "route"
    # nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  tls:
  - hosts:
    - jenkins
  rules:
  - host: jenkins
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-service
          servicePort: 8080