dependencies:
- name: spinnaker
  version: 1.15.0
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: redis.enabled
# - name: docker-registry
#   version: 1.8.0
#   repository: https://kubernetes-charts.storage.googleapis.com
- name: elastic-stack
  version: 1.8.0
  repository: https://kubernetes-charts.storage.googleapis.com
- name: prometheus-operator
  version: 6.4.1
  repository: https://kubernetes-charts.storage.googleapis.com
