{{- if eq .Values.storageClass ""}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins
  labels:
    purpose: jenkins-shared-deployment
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/jenkins/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      purpose: jenkins-shared-deployment

{{- else }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-claim
  labels:
    app: jenkins
    tier: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClass: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 10Gi

{{- end }}