apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kubectl-jenkins-context
data:
  kubectl-config-context.sh: |-
    #!/bin/bash -v

    # # Configure external production cluster using the mounted secrets
    # PROD_CRED_PATH=/secrets/prod-credentials

    # USERNAME=$(cat $PROD_CRED_PATH/username)
    # PASSWORD=$(cat $PROD_CRED_PATH/password)
    # SERVER=$(cat $PROD_CRED_PATH/server)
    # CERTIFICATE_PATH=$PROD_CRED_PATH/ca.crt
    # NAMESPACE="default"
 
    # kubectl config set-credentials prod-admin --username=$USERNAME --password=$PASSWORD
    # kubectl config set-cluster production --server=$SERVER --certificate-authority=$CERTIFICATE_PATH
    # kubectl config set-context production --cluster=production --user=prod-admin --namespace=$NAMESPACE
    # kubectl config use-context production

    # # Create docker-registry secret in production cluster
    # REG_CRED_PATH="/secrets/registry-credentials-pod"
    # REGISTRY_SERVER=$(cat $REG_CRED_PATH/server)
    # REGISTRY_USERNAME=$(cat $REG_CRED_PATH/username)
    # REGISTRY_PASSWORD=$(cat $REG_CRED_PATH/password)
    # REGISTRY_EMAIL=$(cat $REG_CRED_PATH/email)
    # kubectl create secret docker-registry registry-credentials --docker-server=$REGISTRY_SERVER --docker-username=$REGISTRY_USERNAME --docker-password=$REGISTRY_PASSWORD --docker-email=$REGISTRY_EMAIL --dry-run -o yaml | kubectl apply -f -

    cp /root/kube-conf/* /root/.kube/
    
    # Configure kubeconfig entry for local cluster
    kubectl config set-credentials jenkins --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    kubectl config set-cluster kubernetes --server=https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT --certificate-authority="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    kubectl config set-context jenkins-kubernetes --cluster=kubernetes --user=jenkins --namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    kubectl config use-context jenkins-kubernetes
    
    chmod 777 ~/.kube/config
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins
        tier: jenkins
    spec:
      serviceAccountName: jenkins
      initContainers:
      - image: lachlanevenson/k8s-kubectl:v1.11.2
        name: kubectl-config
        command:
        - "/bin/sh"
        args:
        - "/kubectl-config-context.sh"
        volumeMounts:
        - name: kubeconfig
          mountPath: "/root/.kube"
        - name: kubectl-jenkins-context
          mountPath: "/kubectl-config-context.sh"
          subPath: "kubectl-config-context.sh"
        - name: registry-credentials-pod
          mountPath: /secrets/registry-credentials-pod
        - name: kube-conf
          mountPath: root/kube-conf
      containers:
      - image: {{ .Values.image }}
        name: jenkins
        env:
        - name: WSO2_USERNAME
          valueFrom:
            secretKeyRef:
              name: wso2-credentials
              key: username
        - name: WSO2_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wso2-credentials
              key: password
        - name: REGISTRY_SERVER
          valueFrom:
            secretKeyRef:
              name: registry-credentials-pod
              key: server
        - name: REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: registry-credentials-pod
              key: username
        - name: REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: registry-credentials-pod
              key: password
        - name: CASC_JENKINS_CONFIG
          value: "/var/casc_configs"
        - name: PROD_CONFIG_LOCATION
          value: "/var/prod-config"
        imagePullPolicy: Always
        readinessProbe:
          periodSeconds: 10
          exec:
            command:
            - /bin/bash
            - -c
            - wum version
            - docker version
            - kubectl version
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
        - name: docker
          mountPath: /var/run/docker.sock
        - name: jenkins-persistent-storage
          mountPath: /var/jenkins_home
        - name: wso2-credentials
          mountPath: /wso2creds
        - name: jenkins-casc-conf
          mountPath: /var/casc_configs
        ports:
        - containerPort: 8080
          name: jenkins
          protocol: TCP
      volumes:
      - name: kubectl-jenkins-context
        configMap:
          name: kubectl-jenkins-context
          items:
          - key: kubectl-config-context.sh
            path: kubectl-config-context.sh
      - name: kubeconfig
        emptyDir: {}
      - name: docker
        hostPath:
          path: /var/run/docker.sock
      - name: jenkins-persistent-storage
        persistentVolumeClaim:
          claimName: jenkins-claim
      - name: wso2-credentials
        secret:
          secretName: wso2-credentials
      - name: jenkins-casc-conf
        configMap:
          name: jenkins-casc-conf
      - name: registry-credentials-pod
        secret:
          secretName: registry-credentials-pod
      - name: kube-conf
        configMap:
          name: kube-conf