apiVersion: v1
kind: Secret
metadata:
  name: prod-credentials
type: Opaque
data:
  server: {{ .Values.prodEnv.server }}
  username: {{ .Values.prodEnv.username }}
  password: {{ .Values.prodEnv.password }}
  ca.crt: {{ .Values.prodEnv.certificate }}