apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-credentials-pod
data:
  username: {{ .Values.registry.username }}
  password: {{ .Values.registry.password }}
  server: {{ .Values.registry.server }}
  email: {{ .Values.registry.email }}