apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-credentials-pod
data:
  username: {{ .Values.registry.username | b64enc }}
  password: {{ .Values.registry.password | b64enc }}
  server: {{ .Values.registry.server | b64enc }}
  email: {{ .Values.registry.email | b64enc }}