apiVersion: batch/v1
kind: Job
metadata:
  name: spin
spec:
  template:
    spec:
      containers:
      - name: spin
        image: aaquiff/spin
        command: ["/bin/sh"]
        args: ["-c", "sh /spinnaker/run.sh"]
        env:
        - name: SPINNAKER_API
          value: "http://spin-gate.spinnaker.svc.cluster.local:8084"
        volumeMounts:
        - name: spinnaker-conf
          mountPath: /spinnaker
      restartPolicy: Never
      volumes:
      - name: spinnaker-conf
        configMap:
          name: spinnaker-conf
  backoffLimit: 0
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-conf
data:
  run.sh: |-
    cd spinnaker
    spin applications save spintest --file application.json --gate-endpoint http://spin-gate.spinnaker.svc.cluster.local:8084
    spin pipeline save -f pipeline.json --gate-endpoint http://spin-gate.spinnaker.svc.cluster.local:8084
  testapp.yml: |-
    # set application config here
    # the `name` key does not need to be set
    # and will be overridden by the name cli arg
    email: aaquiff@wso2.com
    cloudProviders:
      - kubernetes
    instancePort: 80
  application.json: |-
    {
      "cloudProviders": [
        "aws"
      ],
      "createTs": "1556521904659",
      "email": "aaquiff@wso2.com",
      "instancePort": 81,
      "lastModifiedBy": "anonymous",
      "name": "wso2-demo",
      "providerSettings": {
        "aws": {
        "useAmiBlockDeviceMappings": false
        },
        "gcp": {
        "associatePublicIpAddress": false
        }
      },
      "repoProjectKey": "testapp",
      "repoType": "github",
      "trafficGuards": [],
      "updateTs": "1556521904000"
    }
  pipeline.json: |-
    {
      "application": "wso2-demo",
      "id": "468f37b1-83fe-484a-b2cb-dc8dedff783b",
      "index": 0,
      "keepWaitingPipelines": false,
      "lastModifiedBy": "anonymous",
      "limitConcurrent": true,
      "name": "Demo",
      "stages": [
        {
        "name": "Wait",
        "refId": "1",
        "requisiteStageRefIds": [],
        "type": "wait",
        "waitTime": 30
        }
      ],
      "triggers": [],
      "updateTs": "1556523268000"
    }