apiVersion: batch/v1
kind: Job
metadata:
  name: spin
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      containers:
      - name: spin
        image: aaquiff/spin
        command: ["/bin/sh"]
        args: ["-c", "sh /spinnaker/run.sh"]
        env:
        - name: SPINNAKER_API
          value: "http://spin-gate.{{ .Release.Namespace }}.svc.cluster.local:8084"
        volumeMounts: 
        - name: spinnaker-conf
          mountPath: /spinnaker
      restartPolicy: Never
      volumes:
      - name: spinnaker-conf
        configMap:
          name: spinnaker-conf
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-conf
data:
  run.sh: |-
    cd spinnaker
    until spin application list --gate-endpoint $SPINNAKER_API; do  echo "Retrying in 10s"; sleep 10; done;
    spin applications save spintest --file application.json --gate-endpoint $SPINNAKER_API && spin pipeline save -f pipeline.json --gate-endpoint $SPINNAKER_API
  application.json: |-
    {
      "cloudProviders": "kubernetes",
      "email": "aaquiff@wso2.com",
      "lastModifiedBy": "anonymous",
      "name": "wso2-demo",
      "trafficGuards": [],
      "user": "[anonymous]"
    }
  pipeline.json: |-
    {
      "application": "wso2-demo",
      "expectedArtifacts": [
        {
        "defaultArtifact": {
          "customKind": true,
          "id": "56330e63-2a3a-4979-a432-043e0c653685"
        },
        "displayName": "chart",
        "id": "4397cbfc-50f8-4244-b721-2a35d8e04715",
        "matchArtifact": {
          "id": "7f76f43f-37fd-4410-81f2-c1acd4cf8422",
          "name": ".*\\.tgz",
          "type": "embedded/base64"
        },
        "useDefaultArtifact": false,
        "usePriorArtifact": true
        },
        {
        "defaultArtifact": {
          "customKind": true,
          "id": "1db24043-0cd0-4511-b645-e4fa7f52a689"
        },
        "displayName": "values-staging.yaml",
        "id": "aec2c4f1-2cb2-4d50-962a-dedc2a7457e0",
        "matchArtifact": {
          "id": "d98b429d-0a8e-4c3e-87d1-d57974f0c6ae",
          "name": "values-staging.yaml",
          "type": "embedded/base64"
        },
        "useDefaultArtifact": false,
        "usePriorArtifact": true
        },
        {
        "defaultArtifact": {
          "customKind": true,
          "id": "3b6e0f4b-df2f-4434-a081-b000c0b08c00"
        },
        "displayName": "values-prod.yaml",
        "id": "14234aae-38d8-424b-9d11-76cbade0e194",
        "matchArtifact": {
          "id": "c2ec0634-256c-4ab9-8f81-f1d67ebf6280",
          "name": "values-prod.yaml",
          "type": "embedded/base64"
        },
        "useDefaultArtifact": false,
        "usePriorArtifact": true
        },
        {
        "defaultArtifact": {
          "id": "beebe844-426d-46ee-9a9f-b13eeb251717",
          "name": "{{ .Values.registry.address}}/{{ .Values.dockerRepo.org}}/{{ .Values.dockerRepo.repo}}",
          "reference": "{{ .Values.registry.address}}/{{ .Values.dockerRepo.org}}/{{ .Values.dockerRepo.repo}}",
          "type": "docker/image"
        },
        "displayName": "rotten-catfish-66",
        "id": "ac0f7833-c764-40fc-a37a-f6a546b72db3",
        "matchArtifact": {
          "id": "a8417d7f-2fa1-4d7b-a06b-e9610d5604fa",
          "name": "{{ .Values.registry.address}}/{{ .Values.dockerRepo.org}}/{{ .Values.dockerRepo.repo}}",
          "type": "docker/image"
        },
        "useDefaultArtifact": true,
        "usePriorArtifact": true
        }
      ],
      "id": "0688995b-96d2-410b-b5af-b50f0a3bd0b0",
      "index": 0,
      "keepWaitingPipelines": false,
      "lastModifiedBy": "anonymous",
      "limitConcurrent": true,
      "name": "Deployment Pipeline",
      "stages": [
        {
        "evaluateOverrideExpressions": false,
        "expectedArtifacts": [
          {
          "defaultArtifact": {},
          "displayName": "staging-chart",
          "id": "226a10b2-fa11-4ac0-813e-a4556d574721",
          "matchArtifact": {
            "kind": "base64",
            "name": "wso2ei-staging",
            "type": "embedded/base64"
          },
          "useDefaultArtifact": false
          }
        ],
        "inputArtifacts": [
          {
          "account": "embedded-artifact",
          "id": "4397cbfc-50f8-4244-b721-2a35d8e04715"
          },
          {
          "account": "embedded-artifact",
          "id": "aec2c4f1-2cb2-4d50-962a-dedc2a7457e0"
          }
        ],
        "name": "Bake (Manifest) Staging",
        "namespace": "staging",
        "outputName": "wso2ei-staging",
        "overrides": {
          "imageCredentials.password": "{{ .Values.registry.password }}",
          "imageCredentials.registry": "{{ .Values.registry.address }}",
          "imageCredentials.username": "{{ .Values.registry.username }}"
        },
        "refId": "1",
        "requisiteStageRefIds": [],
        "templateRenderer": "HELM2",
        "type": "bakeManifest"
        },
        {
        "account": "default",
        "cloudProvider": "kubernetes",
        "manifestArtifactAccount": "embedded-artifact",
        "manifestArtifactId": "226a10b2-fa11-4ac0-813e-a4556d574721",
        "moniker": {
          "app": "wso2-demo"
        },
        "name": "Deploy (Manifest) Staging",
        "refId": "2",
        "relationships": {
          "loadBalancers": [],
          "securityGroups": []
        },
        "requiredArtifactIds": [
          "ac0f7833-c764-40fc-a37a-f6a546b72db3"
        ],
        "requisiteStageRefIds": [
          "1",
          "3"
        ],
        "skipExpressionEvaluation": false,
        "source": "artifact",
        "type": "deployManifest"
        },
        {
        "evaluateOverrideExpressions": false,
        "expectedArtifacts": [
          {
          "defaultArtifact": {},
          "displayName": "production-chart",
          "id": "c5dfdee9-9b49-40a1-a241-9bb48a1284aa",
          "matchArtifact": {
            "kind": "base64",
            "name": "production-chart",
            "type": "embedded/base64"
          },
          "useDefaultArtifact": false
          }
        ],
        "inputArtifacts": [
          {
          "account": "embedded-artifact",
          "id": "4397cbfc-50f8-4244-b721-2a35d8e04715"
          },
          {
          "account": "embedded-artifact",
          "id": "14234aae-38d8-424b-9d11-76cbade0e194"
          }
        ],
        "name": "Bake (Manifest) Prod",
        "namespace": "prod",
        "outputName": "wso2ei-prod",
        "overrides": {
          "imageCredentials.password": "{{ .Values.registry.password }}",
          "imageCredentials.registry": "{{ .Values.registry.address }}",
          "imageCredentials.username": "{{ .Values.registry.username }}"
        },
        "refId": "3",
        "requisiteStageRefIds": [],
        "templateRenderer": "HELM2",
        "type": "bakeManifest"
        },
        {
        "account": "default",
        "cloudProvider": "kubernetes",
        "manifestArtifactAccount": "embedded-artifact",
        "manifestArtifactId": "c5dfdee9-9b49-40a1-a241-9bb48a1284aa",
        "moniker": {
          "app": "wso2-demo"
        },
        "name": "Deploy (Manifest) Production",
        "refId": "4",
        "relationships": {
          "loadBalancers": [],
          "securityGroups": []
        },
        "requiredArtifactIds": [
          "ac0f7833-c764-40fc-a37a-f6a546b72db3"
        ],
        "requisiteStageRefIds": [
          "6"
        ],
        "skipExpressionEvaluation": false,
        "source": "artifact",
        "type": "deployManifest"
        },
        {
        "command": "test.sh",
        "failPipeline": true,
        "name": "Test Script",
        "refId": "5",
        "repoBranch": "master",
        "repoUrl": "https://github.com/{{ .Values.sampleRepo.owner }}/{{ .Values.sampleRepo.name }}",
        "requisiteStageRefIds": [
          "2"
        ],
        "scriptPath": "tests",
        "type": "script",
        "user": "[anonymous]",
        "waitForCompletion": true
        },
        {
          "failPipeline": true,
          "isNew": true,
          "judgmentInputs": [],
          "name": "Manual Judgment",
          "notifications": [],
          "refId": "6",
          "requisiteStageRefIds": [
            "5"
          ],
          "type": "manualJudgment"
        }
      ],
      "triggers": [
        {
        "enabled": true,
        "expectedArtifactIds": [
          "4397cbfc-50f8-4244-b721-2a35d8e04715",
          "aec2c4f1-2cb2-4d50-962a-dedc2a7457e0",
          "14234aae-38d8-424b-9d11-76cbade0e194"
        ],
        "payloadConstraints": {},
        "source": "chart",
        "type": "webhook"
        },
        {
        "account": "dockerhub",
        "enabled": true,
        "expectedArtifactIds": [
          "ac0f7833-c764-40fc-a37a-f6a546b72db3"
        ],
        "organization": "{{ .Values.dockerRepo.org }}",
        "registry": "{{ .Values.registry.address }}",
        "repository": "{{ .Values.dockerRepo.org }}/{{ .Values.dockerRepo.repo }}",
        "type": "docker"
        }
      ],
      "updateTs": "1557476159000"
      }
