apiVersion: batch/v1
kind: Job
metadata:
  name: spinnaker-pipeline-creator
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      containers:
      - name: spin
        image: aaquiff/spin
        command: ["/bin/sh"]
        args: ["-c", "sh /spinnaker/run.sh"]
        env:
        - name: SPINNAKER_API
          value: "http://spin-gate.{{ .Release.Namespace }}.svc.cluster.local:8084"
        volumeMounts: 
        - name: spinnaker-conf
          mountPath: /spinnaker
      restartPolicy: Never
      volumes:
      - name: spinnaker-conf
        configMap:
          name: spinnaker-conf
  
---
{{- $root := . -}}
{{- $files := .Files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-conf
data:
  run.sh: |-
    cd spinnaker
    until spin application list --gate-endpoint $SPINNAKER_API; do  echo "Retrying in 10s"; sleep 10; done;
    {{- range .Values.applications }}
    spin applications save spintest --file {{ .name }}.json --gate-endpoint $SPINNAKER_API && \

    spin pipeline save -f {{ .name }}-production-pipeline.json --gate-endpoint $SPINNAKER_API && \
    id=`spin pipelines get --application {{ .name }} --name "Deploy Production" --output=jsonpath={.id} --gate-endpoint $SPINNAKER_API` && \
    echo $id && \
    sed "s|<DEPLOY_PRODUCTION_ID>|$id|" {{ .name }}-staging-pipeline.json > ../{{ .name }}-staging-pipeline.json && \
    cat ../{{ .name }}-staging-pipeline.json && \
    spin pipeline save -f ../{{ .name }}-staging-pipeline.json --gate-endpoint $SPINNAKER_API && \
    id=`spin pipelines get --application {{ .name }} --name "Deploy Staging" --output=jsonpath={.id} --gate-endpoint $SPINNAKER_API` && \
    echo $id && \
    sed "s|<DEPLOY_STAGING_ID>|$id|" {{ .name }}-bake-pipeline.json > ../{{ .name }}-bake-pipeline.json && \
    cat ../{{ .name }}-bake-pipeline.json && \
    spin pipeline save -f ../{{ .name }}-bake-pipeline.json --gate-endpoint $SPINNAKER_API
    {{- end }}
  {{- range .Values.applications }}
  {{ .name }}.json: |-
    {
      "cloudProviders": "kubernetes",
      "email": "{{ .email }}",
      "lastModifiedBy": "anonymous",
      "name": "{{ .name }}",
      "trafficGuards": [],
      "user": "[anonymous]"
    }
  {{- $imageName := printf "%s/%s/%s" .image.registry .image.organization .image.repository }}
  {{- $bakepipeline := printf "%s-%s" .name "bake-pipeline.json" }}
  {{- $stagingpipeline := printf "%s-%s" .name "staging-pipeline.json" }}
  {{- $productionpipeline := printf "%s-%s" .name "production-pipeline.json" }}
  
  {{ ($files.Glob "spinnaker-pipeline-jobs/BakeArtifacts.json").AsConfig | replace "<DOCKER_IMAGE>" $imageName | replace "<IMAGE_REGISTRY>" .image.registry | replace "<IMAGE_USERNAME>" .image.username | replace "<IMAGE_PASSWORD>" .image.password | replace "<IMAGE_ORGANIZATION>" .image.organization | replace "<IMAGE_REPOSITORY>" .image.repository | replace "<APPLICATION>" .name | replace "BakeArtifacts.json" $bakepipeline | nindent 2 }}
  
  {{ ($files.Glob "spinnaker-pipeline-jobs/DeployStaging.json").AsConfig | replace "<DOCKER_IMAGE>" $imageName | replace "<REPO_URL>" .repoUrl | replace "<TESTSCRIPT_COMMAND>" .testScript.command | replace "<TESTSCRIPT_PATH>" .testScript.path | replace "<APPLICATION>" .name | replace "DeployStaging.json" $stagingpipeline | nindent 2 }}

  {{ ($files.Glob "spinnaker-pipeline-jobs/DeployProduction.json").AsConfig | replace "<DOCKER_IMAGE>" $imageName | replace "<APPLICATION>" .name | replace "DeployProduction.json" $productionpipeline | nindent 2 }}

  {{- end }}
