# Github credentials for thea account containing the CI/CD Repositories
github:
  username: <GITHUB_USERNAME>
  password: <GITHUB_PASSWORD>

# Credentials to access the private dockerhub registry
registry:
  server: 'https://index.docker.io/v1/'
  username: <REGISTRY_USERNAME>
  password: <REGISTRY_PASSWORD>
  email: <REGISTRY_EMAIL>
  address: index.docker.io

# Values to configure Spinnaker
spinnaker:
  dockerRegistries:
    - name: dockerhub
      address: index.docker.io
      username: <REGISTRY_USERNAME>
      password: <REGISTRY_PASSWORD>
      email: <REGISTRY_EMAIL>
      # Add each repositories that would be used in the deployment
      repositories:
        - <REGISTRY_USERNAME>/petstore

applications:
  - name: wso2mgw
    email: <EMAIL>
    testScript:
      path: tests
      command: test.sh
    chart:
      customChart: false
      name: microgateway
      version: 3.0.1-1
      repo: 'https://github.com/<GITHUB_ORG>//sample-mgw-chart'
    images:
      - organization: <REGISTRY_USERNAME>
        repository: petstore
        microgateway:
          gitRepository: https://github.com/wso2-incubator//petstore
          

