# Github credentials for thea account containing the CI/CD Repositories
github:
  username: <GITHUB_USERNAME>
  password: <GITHUB_PASSWORD>

# Credentials to access the private dockerhub registry
registry:
  server: 'https://index.docker.io/v1/'
  username: <REGISTRY_USERNAME>
  password: <REGISTRY_PASSWORD>
  email: <REGISTRY_EMAIL>
  address: index.docker.io

# Values to configure Spinnaker
spinnaker:
  dockerRegistries:
    - name: dockerhub
      address: index.docker.io
      username: <REGISTRY_USERNAME>
      password: <REGISTRY_PASSWORD>
      email: <REGISTRY_EMAIL>
      # Add each repositories that would be used in the deployment
      repositories:
        - <REGISTRY_USERNAME>/wso2ei-integrator

applications:
  - name: wso2ei
    email: <EMAIL>
    testScript:
      path: tests
      command: test.sh
    chart:
      customChart: false
      name: ei-pattern-1
      version: 6.5.0-3
      repo: 'https://github.com/wso2-incubator/cicd-sample-chart-ei'
    images:
      - organization: <REGISTRY_USERNAME>
        repository: wso2ei-integrator
        deployment: wso2ei
        customImage:
          baseImage: 'wso2/wso2ei-integrator:6.5.0'
          dockerfileGitRepo: 'https://github.com/wso2-incubator/cicd-sample-docker-ei'
