# Github credentials for thea account containing the CI/CD Repositories
github:
  username: <GITHUB_USERNAME>
  password: <GITHUB_PASSWORD>

# Credentials to access the private dockerhub registry
registry:
  server: 'https://index.docker.io/v1/'
  username: <REGISTRY_USERNAME>
  password: <REGISTRY_PASSWORD>
  email: <REGISTRY_EMAIL>
  address: index.docker.io

# Values to configure Spinnaker
spinnaker:
  dockerRegistries:
    - name: dockerhub
      address: index.docker.io
      username: <REGISTRY_USERNAME>
      password: <REGISTRY_PASSWORD>
      email: <REGISTRY_EMAIL>
      # Add each repositories that would be used in the deployment
      repositories:
        - <REGISTRY_USERNAME>/wso2is

applications:
  - name: wso2is
    email: <EMAIL>
    testScript:
      path: tests
      command: test.sh
    chart:
      customChart: false
      name: is-pattern-1
      version: 5.8.0-3
      repo: 'https://github.com/wso2-incubator/sample-is-chart'
    images:
      - organization: <REGISTRY_USERNAME>
        repository: wso2is
        customImage:
          baseImage: 'wso2/wso2is:5.8.0'
          dockerfileGitRepo: 'https://github.com/wso2-incubator/sample-docker-is'
