apiVersion: v1
entries:
  mysql:
  - appVersion: 5.7.14
    created: 2019-04-12T10:48:42.861337+05:30
    description: Fast, reliable, scalable, and easy to use open-source relational
      database system.
    digest: b276c0449902d4a6d787e6f196ec248f4a56f280514a83f75af1ac12b88d8858
    engine: gotpl
    home: https://www.mysql.com/
    icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
    keywords:
    - mysql
    - database
    - sql
    maintainers:
    - email: o.with@sportradar.com
      name: olemarkus
    - email: viglesias@google.com
      name: viglesiasce
    name: mysql
    sources:
    - https://github.com/kubernetes/charts
    - https://github.com/docker-library/mysql
    urls:
    - https://helm.example.repo.com/charts/mysql-0.13.0.tgz
    version: 0.13.0
generated: 2019-04-12T10:48:42.860372+05:30
