jobs:
  - script: >
      pipelineJob('wso2ei') {
            definition {
              cpsScm {
                scm {
                  github('Aaquiff/kubernetes-ei-cd')
                }
              }
            }
            triggers {
              configure {
                it / 'triggers' << 'com.cloudbees.jenkins.GitHubPushTrigger'{
                    spec''
                }
                scm('* * * * *')
              }
            }
            parameters {
                stringParam('PRODUCT','','WSO2 Product name')
                stringParam('VERSION','','Version of the chosen product')
                stringParam('TIMESTAMP','','WUM timestamp')
              }
      }

